# 模糊抓取订阅链接
- type: webfuzzsub
  options:
    url: https://raw.githubusercontent.com/du5/free/master/sub.list

# 订阅链接
- type: subscribe
  options:
    url: https://proxypool.ednovas.xyz/vmess/sub

- type: subscribe
  options:
    url: https://proxypool.ednovas.xyz/ssr/sub

- type: subscribe
  options:
    url: https://proxypool.ednovas.xyz/trojan/sub

- type: subscribe
  options:
    url: https://zua426.cf/vmess/sub

- type: subscribe
  options:
    url: https://free.zdl.im/vmess/sub

- type: subscribe
  options:
    url: https://www.joemt.tk/vmess/sub

- type: subscribe
  options:
    url: https://proxypoolss.fly.dev/vmess/sub

- type: subscribe
  options:
    url: https://ednovas.design/vmess/sub
    
# 网页模糊抓取
- type: webfuzz
  options:
    url: https://merlinblog.xyz/wiki/freess.html

# tg频道抓取
- type: tgchannel
  options:
    channel: ssrList
    num: 200

- type: tgchannel
  options:
    channel: jingpingziyuanfenxiang
    num: 200
    
- type: tgchannel
  options:
    channel: V2List
    num: 200   

- type: tgchannel
  options:
    channel: ssrshares
    num: 200 

- type: tgchannel
  options:
    channel: jiedianbaipiao
    num: 200 
    
- type: tgchannel
  options:
    channel: SSRSUB
    num: 200 
    
- type: tgchannel
  options:
    channel: Trojan8088
    num: 200 
# 翻墙党论坛抓取
- type: web-fanqiangdang
  options:
    url: https://fanqiangdang.com/forum-48-1.html

# clash格式订阅链接
- type: clash
  options:
    url: https://zua426.cf/clash/proxies?c=HK,TW,JP,KR,US,CA

- type: clash
  options:
    url: https://free.zdl.im/clash/proxies?c=HK,TW,JP,KR,US,CA

- type: clash
  options:
    url: https://www.joemt.tk/clash/proxies?c=HK,TW,JP,KR,US,CA

- type: clash
  options:
    url: https://ednovas.design/clash/proxies?c=HK,TW,JP,KR,US,CA

- type: clash
  options:
    url: https://proxypoolss.fly.dev/clash/proxies?c=HK,TW,JP,KR,US,CA

# 某个网站抓取
- type: web-freessrxyz
  options:
